services:
  calendario-app:
    container_name: calendario-app
    build: .
    restart: always
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=file:/app/data/database.sqlite
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0

  tailscale:
    image: tailscale/tailscale:latest
    container_name: calendario-tsa-tailscale
    hostname: calendario-tsa
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/etc/tailscale/serve.json
    volumes:
      - ./tailscale_state:/var/lib/tailscale
      - ./serve.json:/etc/tailscale/serve.json
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: always
